export default {
  distriText: 'Distribution management',
  pendingTip: 'You are not a distributor yet, the distribution application you submitted is under review, please be patient',
  inputTip: 'Please fill in the application description',
  orderAmount: 'Lump sum',
  getCommission: 'Commission',
  noAppliedTip: 'You are not a distributor yet, you can submit an application to become a distributor after being reviewed by the merchant',
  rejectTip: 'You are not yet a distributor, the distribution application you submitted has not been approved',
  rejectTip1: 'Review rejected:{reason}, you can contact the administrator or resubmit the application',
  applyTip: 'Explain',
  approvedTip: 'Show only commission breakdowns generated by your next level members'
}