/*
 * @Version: 1.0.0
 * @Author: Owen.wang
 * @Date: 2023-01-09
 * @LastEditors: Owen.wang
 * @LastEditTime: 2023-04-04
 * @FilePath: \cb2b-mobile\src\locale\lib\cn\modules\afterSales.js
 * @Description:
 */
module.exports = {
	all: '全部售后',
	unapproved: '待审核',
	noRefund: '待退款',
	noReturn: '待退回',
	noReplace: '待换货',
	afterSalesNo: '售后单号',
	refundOnly: '仅退款',
	exchangeGoods: '换货',
	onlyReturnRefund: '退货退款',
	afterSalesInfo: '售后详情',
	cancelSales: '取消售后',
	confirm: '确认完成',
	sendBack: '寄回',
	courierNumber: '快递单号',
	courierTip: '请输入快递单号',
	backSuccessTip: '提交成功，等待确认',
	ConfirmtocancelSales: '是否确定取消售后',
	ConfirmReceipt: '是否确定售后完成',
	afterSalesSuccess: '售后完成',
	noAfterSales: '暂无售后单',
	returnAddress: '退货地址',
	receiver: '收件人',
	receiverPhone: '收件电话',
	receiverAddress: '收件地址',
	price: '价格',
	orderQuantity: '订购数量',
	afterQuantity: '售后数量',
	exchangeAttribute: '更换规格',
	afterAmount: '售后金额',
	multiShot: '拍多了',
	overtime: '未按约定时间发货',
	consult: '协商一致退款',
	outOfStock: '缺货',
	wrongInfo: '地址/电话信息填写错误',
	doNotWant: '不想要了',
	wrongShooting: '商品信息拍错（规格/尺码/颜色等）',
	other: '其它',
	afterSalesType: '售后类型',
	afterSalesReason: '售后原因',
	orderRemark: '订单备注',
	cretedTime: '申请时间',
	afterSalesList: '售后清单',
	applyAfterSales: '售后申请',
	closeReson: '关闭原因',
	closeReson1: '用户主动取消',
	closeReson2: '商家审核拒绝',
	closeReson3: '退回商品上架拒收',
	closeReson4: '财务审核取消',
	selectAfterProducts: '请选择售后商品',
	applyQuantity: '申请数量',
	amoutTip: '请输入售后金额',
	selectAfterReason: '请选择售后原因',
	checkedMsg: '请至少选择一件需要售后的商品',
	addAfterSaleSuccess: '申请成功',
	selectAfterType: '请选择售后类型',
	canAfterAmount: '订单可售后金额',
	orderNum: '订单号',
	afterSaledNum: '已售后数量',
	change: '更改',
	selectChangeSku: '请选择要更换的规格',
	finishTime: '完成时间',
	closeTime: '关闭时间',
	tipMsg: '请您根据商家提供的退货地址将商品寄回',
	maxAmount: '超过最大可售后金额',
	availableAfterSaleQuantity: '可售后数量',
	messageInfo: '该售后订单未付完尾款，售后金额会根据尾款支付情况计算可退金额'
}
