module.exports = {
	title: '确认订单',
	remark: '备注',
	invoiceType: '发票类型',
	invoiceTypePlaceholder: '请选择发票类型',
	invoiceInfo: '发票信息',
	invoiceTitle: '发票抬头',
	invoiceTax: '纳税号',
	bank: '开户银行',
	name: '开户名称',
	number: '开户账号',
	titleMsg: '请输入发票抬头',
	taxMsg: '请输入纳税号',
	bankMsg: '请输入开户银行',
	nameMsg: '请输入开户名称',
	numberMsg: '请输入开户账号',
	lengthMsg: '超出最大输入长度',
	newAddress: '使用新地址',
	productTotal: '商品总计（件）',
	productTotalPrice: '订单总金额',
	orderPrice: '实付总金额',
	deposit: '定金',
	finalPayment: '尾款',
	submitOrder: '提交下单',
	submitSuccess: '提交成功',
	locationInfo: '收货地址信息',
	emial: '邮编',
	default: '默认',
	updateLocation: '改为默认地址',
	editAndAdd: '编辑/添加',
	delete: '删除',
	addressCheck: '请填写收货地址',
	invoiceCheck: '请填写完整的发票信息',
	NoInvoicing: '不开发票',
	GeneralVATinvoice: '增值税普通发票',
	VATspecialinvoice: '增值税专用发票',
	ViewOrder: '查看订单',
	orderApprove: '订单提交成功，待审核通过后支付订单金额',
	back: '返回',

	confirmOrder: '是否确认下单？',

	addNewRess: '添加新地址',
	addInvoice: '添加发票',
	invoiceSelect: '选择发票',
	invoice: '发票',
	regionStop: '该地区暂不支持配送'
}
