module.exports = {
	deliveryAddress: '收货地址',
	name: '收货人姓名',
	entername: '请输入收货人姓名',
	inphone: '联系电话',
	contactInphone: '请输入联系电话',
	prefix: '区号',
	location: '国家/地区',
	country: '国家/地区',
	province: '省',
	city: '市',
	area: '区',
	defaultLocation: '请输入详细地址',
	zipCode: '邮编',
	enterZipCode: '请输入邮编',
	setDefault: '设为默认收货地址',
	cancel: '取消',
	sure: '确定',
	exceed: '具体地址不能超过300字',
	please: '请输入手机号',
	again: '您输入的手机号格式有误，请重新输入',
	select: '请选择',

	length: '长度在 1 到 50 个字符',
	enterEare: '请选择区域',
	enterCountry: '请选择完整的国家/地区',
	enterLocation: '请输入具体地址',
	areaCode: '请输入区号',
	editAddress: '编辑地址',

	detailAddress: '详细地址',
	addAddress: '添加收货地址',
	noMore: '暂时没有更多地址',
	exced: '地址最多添加20条',
	inputKeyWord: '请输入搜索关键词'
}
