/*
 * @Version: 1.0.0
 * @Author: Owen.wang
 * @Date: 2022-09-13
 * @LastEditors: Owen.wang
 * @LastEditTime: 2023-05-19
 * @FilePath: \cb2b-mobile\src\locale\lib\cn\modules\order.js
 * @Description:
 */
module.exports = {
	info: '订单详情',
	commodityDetails: '商品明细',
	orderNumber: '订单编号',
	orderTime: '下单时间',
	paymentMethod: '支付方式',
	offlinePayment: '线下支付',
	receivingInformation: '收货信息',
	invoice: '发票',
	noInvoiceRequired: '不需要发票',
	orderRemarks: '订单备注',
	PaymentStatus: '支付状态',
	AccountingPeriod: '账期',
	FullPayment: '全款',
	Deposit: '定金',
	balancePayment: '尾款',
	ToBePaid: '待付',
	PaymentDetails: '支付明细',
	PaymentMethod: '支付方式',
	PaymentAmount: '支付金额',
	ConfirmationTime: '确认时间',
	OrderManagement: '订单管理',
	inputOrderNumber: '订单编号',
	startTime: '开始日期',
	endTime: '结束日期',
	query: '查询',
	noOrder: '暂时没有更多订单',
	addOrder: '全部订单',
	awaitReviewed: '待审核',
	awaitPay: '待付款',
	awaitDilive: '待发货',
	partDilive: '部分发货',
	hasDilive: '待收货',
	finish: '已完成',
	close: '已关闭',
	OrderCreationTime: '订单创建时间',
	OrderDeliveryTime: '订单发货时间',
	DueaccountingPeriod: '账期到期时间',
	UN_PAY: '待付定金',
	PART_DEPOSIT: '部分定金',
	UN_RETAINAGE: '待付尾款',
	PART_RETAINAGE: '部分尾款',
	PID_RETAINAGE: '已付尾款',
	AuditRejection: '审核拒绝',
	retreat: '退',
	Specifications: '规格',
	UnitPrice: '单价',
	advanceRatio: '预付比例',
	cancelOrder: '取消订单',
	orderInfo: '订单详情',
	ConfirmReceipt: '是否确认收货？',
	ConfirmReceipt1: '确认收货 ',
	grossTotal: '订单总金额',
	paidAmount: '已付金额',
	unPayAmount: '待付金额',
	expireTime: '账期到期时间',
	hasEnd: '已到期',
	noEnd: '未到期',
	goodInfo: '商品信息',
	about: '合同条款相关',
	payInfo: '支付信息',
	status: '订单状态',
	operator: '操作',
	day: '天',
	reservePay: '预付',
	Dueaccounting: '账期到期',
	Confirmtocanceltheorder: '是否确认取消订单？',
	ConfirmReceipt2: '是否确认收货？',
	price: '价格',
	immediatePay: '立即支付',
	payAmoutTip: '您的余额不足，请充值后再支付或选择其他支付方式',

	pay: '支付',
	paymentMethod: '支付方式',
	payRecord: '付款记录',
	toBeConfirm: '待确认',
	approved: '已确认',
	canceled: '已取消',
	downloadPi: '下载PI',
	logisticsDetails: '物流详情',
	detailsInfo: '详细信息',
	package: '包裹',
	packageTotal: '此订单包含{n}个包裹',
	express: '物流公司',
	expressNo: '物流单号',
	track: '物流轨迹',
	totalProduct: '物流单包含{n}件商品',
	totalTip: '共{n}件',
	paySuccess: '恭喜你，支付完成',
	back: '返回首页',
	viewOrder: '查看订单',
	rechargeTip: '恭喜你，充值成功',
	refundOrAfterSale: '退款/售后',
	invoiceList: '发票管理',
	editInvoice: '编辑发票',
	addInvoice: '新增发票',
	cancelOrderTip: '该订单有未确认收支，是否确认取消订单'
}
