module.exports = {
	name: '钱包',
	myBalance: '我的余额',
	balanceDetail: '明细',
	accountBan: '账户余额',
	recharge: '充值',
	rechargeBalance: '余额充值',
	addBalance: '余额调整 - 充值',
	debuctBalance: '余额调整 - 扣除',
	orderPay: '订单收款',
	orderRefund: '订单退款',
	cashout: '提现',
	cashAmount: '提现金额',
	allCashAmount: '可提现余额',
	time: '时间',
	inAndexStatus: '收支状态',
	withdrawal: '余额提现',
	distributionRebate: '分销返佣',
	orderType: '订单类型',
	currency: '币种',
	commission: '佣金管理',
	withDrawalListTip: '已结算佣金将会到账您的余额账户，可以在余额中提现或下单使用',
	commissionDetail: '佣金明细',
	cashSuccess: '提现成功',
	cashAmount: '提现金额必须大于0',
	maxCashAmount: '超过可提现金额',
	allCashout: '全部提现',
	commisTotal: '累计获得佣金',
	startTime: '开始时间',
	endTime: '结束时间',
	cashImmedia: '立即提现',
	shareDistri: '邀请用户',
	copyLink: '复制链接',
	viewDetail: '查看明细',
}
